# Stage 1
FROM node:18.16 as node
WORKDIR /app
COPY . .
RUN yarn install
RUN npm run build-dev

# Stage 2
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=node /app/dist/geolink-client /usr/share/nginx/html
