version: '3.4'

services:
  #geolink.identity:
  #  image: ${DOCKER_REGISTRY-}geolinkidentity
  #  container_name: geolink-identity
  #  build:
  #    context: .
  #    dockerfile: GeoLink.Identity/Dockerfile
  #  ports:
  #    - "7001:443"
  #  networks:
  #    - geolink
  
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    container_name: geolink-oracle
    ports:
      - "1521:1521"
    networks:
      - geolink
      
networks:
  geolink:
    driver: bridge
